### PR TITLE
fix: no logout on bad login

### LINKED ISSUE #3832: Failed login attempt is invaliding active session
## Describe the bug

```
$ INFRA_PASSWORD=password infra login infra.infrahq.lvh.me --user admin@local
  Logging in to infra.infrahq.lvh.me
  Logging in as user admin@local
  Logged in as admin@local
$ infra list
You have not been granted access to any active destinations
$ INFRA_PASSWORD=notpassword infra login infra.infrahq.lvh.me --user admin@local
  Logging in to infra.infrahq.lvh.me
  Logging in as user admin@local
Error: Login error: your username or password may be invalid.
$ infra list
Access key is expired, please `infra login` again: access key expired
```

## Expected behavior

A failed login attempt should not invalidate an active session since it should not update any configuration

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

A bad login attempt should not invalid a valid active session. This was regression caused by the `OnUnauthorized` callback which forces a logout on all `Unauthorized` API requests. It's still a good idea in most cases, just not for a bad login.

Resolves #3832

### CODE REVIEW

File: internal/cmd/login.go [hunk 1]
```diff
@@ -294,8 +294,9 @@ func newLoginClient(cli *CLI, options loginCmdOptions) (loginClient, error) {
 		SkipTLSVerify:      options.SkipTLSVerify,
 	}
 	client, err := NewAPIClient(&APIClientOpts{
-		Host:      options.Server,
-		Transport: httpTransportForHostConfig(cfg),
+		Host:                     options.Server,
+		Transport:                httpTransportForHostConfig(cfg),
+		SkipLogoutOnUnauthorized: true,
```
Comment (BruceMacD) [inline internal/cmd/login.go:299]:
```suggestion
		SkipLogoutOnUnauthorized: true, // if a user fails to login, any current sessions they have should remain active
```

For future readers

**Review by BruceMacD — APPROVED** [review]
