### PR TITLE
fix: respect context namespace if overwritten by user

### LINKED ISSUE #2259: Setting a default namespace in the current context is overridden by infra
## Describe the bug

When setting a default namespace for the current context, using either:
```
❯ kubectl config set-context <context> --namespace=<some namespace>
```

or with [kubens](https://github.com/ahmetb/kubectx/blob/master/kubens)

the default namespace reverts back to `default` after a short period.

## Expected behavior

when setting a default namespace in the context, it should be preserved.

## Environment

```
❯ infra version

 Client: 0.13.3
 Server: 0.13.1
```

```
❯ k version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

Respect the users namespace configuration for contexts that do not specify a namespace. Note, if the context is removed through logout or session timeout, the namespace configuration will also be reset. 

If a context managed by infra should have a context, reset it if there's a mismatch.

## Checklist

- [x] Wrote appropriate unit tests
- [ ] Considered security implications of the change
- [ ] Updated associated docs where necessary
- [ ] Updated associated configuration where necessary
- [ ] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [ ] Nothing sensitive logged
- [ ] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2259

### CODE REVIEW

File: internal/cmd/kubernetes.go [hunk 1]
```diff
@@ -151,12 +151,23 @@ func writeKubeconfig(user *api.User, destinations []api.Destination, grants []ap
 			CertificateAuthorityData: ca,
 		}
 
-		kubeConfig.Contexts[context] = &clientcmdapi.Context{
-			Cluster:   context,
-			AuthInfo:  user.Name,
-			Namespace: namespace,
+		kubeContext, ok := kubeConfig.Contexts[context]
```
Comment (BruceMacD) [inline internal/cmd/kubernetes.go:154]: nit: Could be nice to have a comment for future readers so that they understand this is preserving whatever namespaces the user has defined in their default context.

**Review by BruceMacD — APPROVED** [review]
