### PR TITLE
fix: ssh delete modal

### LINKED ISSUE #4005: Typos with delete modal for SSH destinations
* "selected destination"
* Missing capitalization

Screenshot 2023-01-11 at 9 34 36 PM

### PR DESCRIPTION
**Pull request by hoyyeva**
## 📷 
Screen Shot 2023-01-12 at 4 59 23 PM

## Related Issues

Resolves #4005

### CODE REVIEW

File: ui/pages/destinations/index.js [hunk 1]
```diff
@@ -178,7 +178,7 @@ export default function Destinations() {
           setOpenSelectedDeleteModal(false)
         }}
         title={'Remove SSH'}
```
Comment (jmorganca) [inline ui/pages/destinations/index.js:180]:
```suggestion
        title={'Remove destination'}
```

**Review by jmorganca — APPROVED** [review]
LGTM – suggest we call these "destinations" vs SSH, Kubernetes, etc.
