### PR TITLE
fix: create connector identity for org

### LINKED ISSUE #2946: connector creation skipped in org signup

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
When an org signs up they need a connector identity to start adding destinations. Create it by default.

Tests dependent on #2952 

## Checklist

- [x] Considered security implications of the change
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged

## Related Issues

Resolves #2946

### CODE REVIEW

File: internal/cmd/users.go [hunk 1]
```diff
@@ -348,7 +348,13 @@ func updateUser(cli *CLI, name string) error {
 }
 
 func getUserByNameOrID(client *api.Client, name string) (*api.User, error) {
-	users, err := client.ListUsers(api.ListUsersRequest{Name: name})
+	showSystem := false
+
+	if name == "connector" {
```
Comment (pdevine) [inline internal/cmd/users.go:353]: Did you want to use `models.InternalInfraConnectorIdentityName` here as well?

File: internal/server/data/data_test.go [hunk 2]
```diff
@@ -138,44 +138,51 @@ func TestDatabaseSelectors(t *testing.T) {
...
-		letters := make([]string, 0, 26)
+		alphabeticalIdentities := []string{}
 		for r := 'a'; r < 'a'+26; r++ {
-			letters = append(letters, string(r))
+			alphabeticalIdentities = append(alphabeticalIdentities, string(r))
 			g := &models.Identity{Name: string(r)}
 			assert.NilError(t, CreateIdentity(db, g))
 		}
 
+		alphabeticalIdentities = append(alphabeticalIdentities, models.InternalInfraConnectorIdentityName)
```
Comment (pdevine) [inline internal/server/data/data_test.go:148]: Why add the connector identity? Seems like a lot of trouble for just seeing it paginate correctly.

**Review by pdevine — APPROVED** [review]
Overall looks good. The `TestPaginationSelector` test seems a little strange, but looks like it should work fine.

File: internal/cmd/users.go (hunk 1 above)
Comment (BruceMacD) [reply internal/cmd/users.go:353]: We use the name directly in `cmd` to avoid importing the models.

File: internal/server/data/data_test.go (hunk 2 above)
Comment (BruceMacD) [reply internal/server/data/data_test.go]: Good call-out, it made more sense to remove the connector identity from the returned list of all identities. Made that change.
