### PR TITLE
Fix latency caused by high volumes of requests from the same user

### LINKED ISSUE #3944: `POST /api/grants`  and `POST /api/tokens` results in high latency
When making post requests to `/api/grants`, the requests can take anywhere from 3-5s

### PR DESCRIPTION
**Pull request by dnephin**
## Summary

Fixes #3944

This PR fixes the request latency by avoiding the database row lock that was causing the contention. The `UPDATE` queries for `LastSeenAt` are changed to use `WHERE id IN (SELECT ... FOR UPDATE SKIP LOCKED)`.  If two requests are received at roughly the same time, the first request to run `UPDATE` will perform the update. The second request will match no rows, so won't acquire a lock. These new queries also use `WHERE updated_at = ?` to prevent clobbering previous updates.

We use this same pattern in 3 places: access keys, users, and destinations. This PR updates all 3 to use the same approach.

There is one more small bug fix in here as well.  I'll add more comments inline to explain the changes. 

The first commit in this PR attempted to fix the problem by removing the transaction. That did fix the problem, but doubled the request latency in the common case. So I restored the transaction and worked to fix the queries.

### Testing

I wasn't able to reproduce the exact scenario without introducing a sleep. I believe that's because in tests our database runs on the same host, so there is no network latency between the API server and the DB.

[dnephin/test-case](https://github.com/infrahq/infra/compare/dnephin/test-case) adds a test case and a 200ms sleep in the middle of the middleware transaction. When this test is run on `main` the elapsed times range from 20 seconds down to 200ms. When it's run on this branch the elapsed times are in the range of 500ms down to 200ms. I believe this shows the changes here fix the problem because the worse case scenario decreases from 20s to 500ms.

TODO:
* [x] more test coverage of the new `FromOrganization` query option

### CODE REVIEW

File: internal/server/data/access_key.go [hunk 1]
```diff
@@ -297,19 +295,47 @@ func ValidateRequestAccessKey(tx *Transaction, authnKey string) (*models.AccessK
...
-		// same value as server.lastSeenUpdateThreshold.
-		if t.InactivityTimeout.Sub(origTimeout) > 2*time.Second {
-			if err := UpdateAccessKey(tx, t); err != nil {
-				return nil, err
-			}
-		}
 	}
 
-	return t, nil
+	err = updateAccessKeyLastSeenAt(tx, t)
```
Comment (dnephin) [inline internal/server/data/access_key.go:301]: This also fixes the problem where only access keys with an `InactivityTimeout` have the correct `LastSeenAt`. With this change we update the access key even if it doesn't have an `InactivityTimeout`, so the artificial `LastSeenAt` (based on `UpdatedAt`) should be correct now.

File: internal/server/data/destination.go [hunk 2]
```diff
@@ -51,6 +51,37 @@ func UpdateDestination(tx WriteTxn, destination *models.Destination) error {
 	return update(tx, (*destinationsTable)(destination))
 }
 
+// UpdateDestinationLastSeenAt sets dest.LastSeenAt to now and then updates the
+// user row in the database. Updates are throttled to once every 2 seconds.
```
Comment (BruceMacD) [inline internal/server/data/destination.go:55]:
```suggestion
// row in the database. Updates are throttled to once every 2 seconds.
```

**Review by BruceMacD — APPROVED** [review]

File: internal/server/data/provider.go [hunk 3]
```diff
@@ -54,6 +54,10 @@ type GetProviderOptions struct {
 	// KindInfra instructs GetProvider to return the infra provider. There should
 	// only ever be a single provider with this kind for each org.
 	KindInfra bool
+
+	// FromOrganization is the organization ID of the provider. When set to a
+	// non-zero value the organization ID from the transaction is ignored.
+	FromOrganization uid.ID
```
Comment (jmorganca) [inline internal/server/data/provider.go:60]:
```suggestion
	ByOrganization uid.ID
```

File: internal/server/data/access_key.go [hunk 4]
```diff
@@ -297,19 +295,47 @@ func ValidateRequestAccessKey(tx *Transaction, authnKey string) (*models.AccessK
...
+	return t, err
+}
+
+// lastSeenUpdateThreshold is the duration of time that must pass before a
+// LastSeenAt value for a user, access key, or destination is updated again.
+// This prevents excessive writes when a single user performs many requests
+// in a short period of time.
+const lastSeenUpdateThreshold = 2 * time.Second
```
Comment (jmorganca) [inline internal/server/data/access_key.go:309]: Do we need to throttle this if we're skipping locked rows below anyways?

File: internal/server/data/access_key.go (hunk 1 above)
Comment (jmorganca) [reply internal/server/data/access_key.go:301]: Great fix!!

File: internal/server/data/destination.go [hunk 5]
```diff
@@ -60,14 +91,24 @@ type GetDestinationOptions struct {
 	ByUniqueID string
 	// ByName instructs GetDestination to return the row matching this name.
 	ByName string
+
+	// FromOrganization is the organization ID of the provider. When set to a
```
Comment (jmorganca) [inline internal/server/data/destination.go:95]: > FromOrganization is the organization ID of the provider

More of a nit/suggestion: `ByOrganization` for consistency?

**Review by jmorganca — COMMENTED** [review]
Great fix! Some minor comments

File: internal/server/data/destination.go (hunk 5 above)
Comment (dnephin) [reply internal/server/data/destination.go:95]: We have some other variations for these field names (ex: `CreatedBy`, `NotIDs`).

My thinking is that we want something different for `Organization` to make it clear this field works differently from others. `FromOrganization` is an override for the `tx.OrganizationID()`, not simply a new filter being applied to the query.

File: internal/server/data/access_key.go (hunk 4 above)
Comment (dnephin) [reply internal/server/data/access_key.go:309]: Good question. I think each of these has a different purpose. The throttling helps reduce the total number of DB queries, where as the skip locked is to prevent queries from blocking each other. If the API requests are spaced out by 200ms or so then the skip locked doesn't do anything, but throttling will still help us skip a good number of database updates.

The throttling is an optimization, so we don't absolutely need it, but reducing the number of updates is still really nice to keep load off the database. Since it's only 3 lines I'd still like to keep it.

**Review by jmorganca — APPROVED** [review]
