### PR TITLE
fix: stop user from removing the last admin

### LINKED ISSUE #1744: Admins can delete original admin user's grant
Steps to reproduce:

1. Signup as admin user
2. Add additional users and grant them the `admin` role on `infra`
3. Log in as another user
4. Revoke the original admin user's grant

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

Block users from removing the last infra admin from the system. Admins have the permissions to remove other admins but this can lead to a situation where no admins remain making it more the service more difficult to manage.

## Checklist

- [ ] Wrote appropriate unit tests
- [ ] Considered security implications of the change
- [ ] Updated associated docs where necessary
- [ ] Updated associated configuration where necessary
- [ ] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [ ] Nothing sensitive logged
- [ ] Considered data migrations for smooth upgrades

## Related Issues

Resolves #1744

### CODE REVIEW

File: internal/cmd/logout.go [hunk 1]
```diff
@@ -165,14 +165,14 @@ func logoutOne(clear bool, server string) error {
 		return fmt.Errorf("Failed to logout of server %s due to an internal error: %w.", host.Host, err)
 	}
 	if success {
-		fmt.Fprintf(os.Stderr, "Logged out of server %s", host.Host)
+		fmt.Fprintf(os.Stderr, "Logged out of server %s\n", host.Host)
```
Comment (jmorganca) [inline internal/cmd/logout.go:168]: Separate PR?

File: internal/cmd/identities.go [hunk 2]
```diff
@@ -200,6 +200,8 @@ $ infra identities remove machine-a`,
 				}
 			}
 
+			fmt.Fprintf(cli.Stderr, "Deleted identity %q\n", name)
```
Comment (jmorganca) [inline internal/cmd/identities.go:203]: Separate PR?

File: docs/getting-started/quickstart.md [hunk 3]
```diff
@@ -84,7 +84,7 @@ infra login <INFRA_SERVER_HOSTNAME> --skip-tls-verify
 Generate an access key named `key` to connect Kubernetes clusters:
 
 ```
-infra keys add connector-key connector
+infra keys add connector
```
Comment (jmorganca) [inline docs/getting-started/quickstart.md:87]: possible to make separate PR for this one?

File: internal/server/handlers_test.go [hunk 4]
```diff
@@ -888,3 +888,84 @@ func TestAPI_CreateAccessKey(t *testing.T) {
...
+func TestAPI_DeleteGrant(t *testing.T) {
+	srv := setupServer(t, withAdminIdentity)
+	routes := srv.GenerateRoutes(prometheus.NewRegistry())
+
+	user := &models.Identity{Name: "non-admin"}
+
+	err := data.CreateIdentity(srv.db, user)
+	assert.NilError(t, err)
+
+	t.Run("LastInfraAdminGrant", func(t *testing.T) {
```
Comment (jmorganca) [inline internal/server/handlers_test.go:901]: nit: better names

`"last infra admin grant is not deleted"`

File: internal/server/handlers_test.go [hunk 5]
```diff
@@ -888,3 +888,84 @@ func TestAPI_CreateAccessKey(t *testing.T) {
...
+		req := httptest.NewRequest(http.MethodDelete, fmt.Sprintf("/v1/grants/%s", infraAdminGrants[0].ID), nil)
+		req.Header.Set("Authorization", "Bearer "+adminAccessKey(srv))
+
+		resp := httptest.NewRecorder()
+		routes.ServeHTTP(resp, req)
+
+		assert.Equal(t, resp.Code, http.StatusForbidden, resp.Body.String())
+	})
+
+	t.Run("NotLastInfraAdminGrant", func(t *testing.T) {
```
Comment (jmorganca) [inline internal/server/handlers_test.go:915]: nit: better name

`"last-non infra grant is deleted"`

File: internal/server/handlers_test.go [hunk 6]
```diff
@@ -888,3 +888,84 @@ func TestAPI_CreateAccessKey(t *testing.T) {
...
+		req := httptest.NewRequest(http.MethodDelete, fmt.Sprintf("/v1/grants/%s", grant2.ID), nil)
+		req.Header.Set("Authorization", "Bearer "+adminAccessKey(srv))
+
+		resp := httptest.NewRecorder()
+		routes.ServeHTTP(resp, req)
+
+		assert.Equal(t, resp.Code, http.StatusNoContent, resp.Body.String())
+	})
+
+	t.Run("NotInfraAdminGrant", func(t *testing.T) {
```
Comment (jmorganca) [inline internal/server/handlers_test.go:934]: `"last non-infra admin grant is deleted"`

**Review by jmorganca — APPROVED** [review]
