### PR TITLE
fix: delete users from specific identity provider

### LINKED ISSUE #2838: Consolidate duplicate code paths for deleting users
@j-sneh noticed this while working on #2767

Today we have the following:
* `access.DeleteIdentity` - handles removing credentials, access keys, and grants associated with the identity, and #2767 adds removal of `identities_group` references
* `data.DeleteIdentity` - only deletes the one row from `identities` table
* `data.DeleteIdentities` - handles removing grants, and #2767 adds removal of `identities_group` references
* `Server.loadUsers` (from server config) - calls `data.DeleteIdentities` but does not remove credentials, or access keys for the users
* `access.DeleteProviders` - calls `data.DeleteIdentities` and handles deleting access keys (doesn't need to delete credentials)

With #2767 merged it seems like the only gap may be `loadUsers` not deleting  of credentials or access keys. I'm not sure if that is by design.

The problem now is that there are two ways to delete users, in one code path the logic to delete associations is handled in `access`, and in the other code path it's handled in `data`. 

This issue is to clean this up so that at the very least the two flows are consistent about where associations are deleted, either `access` or `data`. Ideally we would also remove the need to have separate code paths for deleting one identity and deleting many identities, but I'm not sure if that's possible.

### LINKED ISSUE #3397: When an identity is soft-deleted provider user records should be removed
## Describe the bug
When an identity is deleted we don't clean up the "provider_user" records that correspond with this identity. These records are used to track where an identity exists, but do not provide an access.

## Expected behavior
When the identity record that corresponds to a "provider_user" record is deleted we should also remove the "provider_user" tracking.

## Environment

```
$ infra version
Client: 0.15.2
```

### PR DESCRIPTION
**Pull request by BruceMacD**
- infra users command adds/removes from the infra identity provider specifically
- consolidate identity deletion logic
- delete identity when it no longer exists in any identity provider

## Summary
When a user is deleted using `infra users add` or `infra users rm` only delete the resources associated with the identity through the Infra provider. Users from other identity providers can be removed by removing the associated provider, or through SCIM (soon).

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #3397
Resolves #2838

### CODE REVIEW

File: internal/access/identity.go [hunk 1]
```diff
@@ -60,39 +59,7 @@ func DeleteIdentity(c *gin.Context, id uid.ID) error {
...
-		}
-	}
-
-	err = data.DeleteGrants(db, data.DeleteGrantsOptions{BySubject: uid.NewIdentityPolymorphicID(id)})
-	if err != nil {
-		return fmt.Errorf("delete identity creds: %w", err)
-	}
-
-	return data.DeleteIdentity(db, id)
+	return data.DeleteIdentities(db, data.InfraProvider(db).ID, data.ByID(id))
```
Comment (dnephin) [inline internal/access/identity.go:62]: I think this change also fixes #2838

File: internal/server/data/identity.go [hunk 2]
```diff
@@ -161,31 +163,61 @@ func DeleteIdentities(tx GormTxn, selectors ...SelectorFunc) error {
...
+	return nil
+}
+
+func deleteReferencesToIdentities(tx GormTxn, providerID uid.ID, toDelete []models.Identity) (unreferencedIdentityIDs []uid.ID, err error) {
+	for _, i := range toDelete {
+		if err := DeleteAccessKeys(tx, DeleteAccessKeysOptions{ByIssuedForID: i.ID, ByProviderID: providerID}); err != nil {
+			return []uid.ID{}, fmt.Errorf("delete identity access keys: %w", err)
+		}
+		// if an identity does not have credentials in the Infra provider this won't be found, but we can proceed
+		credential, err := GetCredential(tx, ByIdentityID(i.ID))
```
Comment (dnephin) [inline internal/server/data/identity.go:184]: I'm not sure if this is correct. I believe we can get here from `data.DeleteProvider`, and if someone deletes an `okta` provider, won't this now delete the users infra credentials as well (because `data.DeleteIdentities` removes credentials by identity ID) ?

**Review by dnephin — COMMENTED** [review]
Looks great! I think this will resolves a couple problems.

There are a lot of calls to `DeleteIdentity` so I think I'll need another pass to think through all those scenarios and see how it matches up to our test coverage.  Left a few questions from my first pass.

File: internal/access/identity.go (hunk 1 above)
Comment (BruceMacD) [reply internal/access/identity.go:62]: Didn't know this was out there, this PR will close this issue also

File: internal/server/config.go [hunk 3]
```diff
@@ -902,6 +902,12 @@ func (s Server) loadUser(db data.GormTxn, input User) (*models.Identity, error)
 		if err := data.CreateIdentity(db, identity); err != nil {
 			return nil, err
 		}
+
+		_, err = data.CreateProviderUser(db, data.InfraProvider(db), identity)
```
[the remark this answers is not in the document]
Comment (BruceMacD) [reply internal/server/config.go:906]: `CreateCredential` creating the provider user would make a lot of sense, but the limitation there at the moment is that user can be declared in grants without having a credential linked to them.

Ex:
```
infra grants add dne@example.com infra --role admin --force
Created user "dne@example.com"
Created grant to "infra" for "dne@example.com"
```

File: internal/access/identity_test.go [hunk 4]
```diff
@@ -53,6 +53,9 @@ func TestDeleteIdentityCleansUpResources(t *testing.T) {
 	err := data.CreateIdentity(db, identity)
 	assert.NilError(t, err)
 
+	_, err = data.CreateProviderUser(db, infraProvider, identity)
+	assert.NilError(t, err)
```
[the remark this answers is not in the document]
Comment (BruceMacD) [reply internal/access/identity_test.go:57]: The assertion that it is missing is down in line 98:
```
_, err = data.GetAccessKeyByKeyID(db, keyID)
assert.ErrorIs(t, err, internal.ErrNotFound)
```

[the remark this answers is not in the document]
Comment (dnephin) [reply internal/access/identity_test.go:57]: How does the access key not found relate to the provider user?

[the remark this answers is not in the document]
Comment (BruceMacD) [reply internal/access/identity_test.go:57]: Apologies, I was on the wrong branch locally, so I looked at the wrong line number here. I added the assertion that the provider user is deleted to this test.

File: internal/server/data/identity.go (hunk 2 above)
Comment (BruceMacD) [reply internal/server/data/identity.go]: Good catch, added a check to not delete credentials when not removing an identity from the infra provider and test for this case.

File: internal/server/data/identity_test.go [hunk 5]
```diff
@@ -143,31 +145,91 @@ var cmpModelsIdentityShallow = cmp.Comparer(func(x, y models.Identity) bool {
...
+					Kind: models.ProviderKindOIDC,
+				}
+				err = CreateProvider(tx, provider)
+				assert.NilError(t, err)
+
+				_, err = CreateProviderUser(tx, provider, id)
+				assert.NilError(t, err)
+
+				return provider.ID, *id
+			},
```
Comment (dnephin) [inline internal/server/data/identity_test.go:206]: Do we have any test coverage to show that groups and grants are removed when it's the last providerUser, and not removed when it's not the last user?

File: internal/server/data/identity.go [hunk 6]
```diff
@@ -161,31 +163,63 @@ func DeleteIdentities(tx GormTxn, selectors ...SelectorFunc) error {
...
+		// if this identity only exists from an infra identity provider, remove all their groups and grants, then delete the user
+		user, err := GetIdentity(tx, Preload("Providers"), ByID(i.ID))
 		if err != nil {
-			return err
+			return []uid.ID{}, fmt.Errorf("check user providers: %w", err)
 		}
 
-		for _, group := range groups {
-			err = RemoveUsersFromGroup(tx, group.ID, []uid.ID{i.ID})
+		if len(user.Providers) == 0 {
```
Comment (dnephin) [inline internal/server/data/identity.go:206]: I don't think I follow this comment. This happens when they are removed from the last provider (regardless of which provide it was), doesn't it? Or because we don't call this from `UpdateIdentityInfoFromProvider` then presumably the last provider was infra?

**Review by dnephin — APPROVED** [review]
`DeleteIdentities` does a lot of things, and I think we might be missing assertions for the conditional removal of grants and groups. With that test coverage I think this looks great!

Should `access.UpdateIdentityInfoFromProvider` be calling `data.DeleteIdentities` now to clean up? It's currently only deleting the access key and provider_user, but I would expect it to need to do more if that was the last provider.

File: internal/server/data/identity.go (hunk 6 above)
Comment (BruceMacD) [reply internal/server/data/identity.go]: This was a bad comment, fixed
