### PR TITLE
fix: keep jwt nonce for version compatibility

### LINKED ISSUE #2081: Removing the JWT nonce is not backwards compatible
## Describe the bug
The nonce on the JWT is marked as a required field on claims in v0.13.0 and earlier.

## Expected behavior
The nonce is not needed, it should not be added to the JWT. For a smooth transition we should update the claims to not require a nonce. Then eventually remove it.

## Environment

```
$ infra version
```

```
$ kubectl version
```

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
This JWT nonce is not needed, but it is marked as required on the claims struct so the struct will fail validation on previous versions of infra without this field. This is a transitional change that makes the `nonce` not required, we can remove it fully in a few versions when 0.13.0 connectors have been phased out.

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated docs where necessary
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2081
Re-opened #2014 to track removing this completely.

### CODE REVIEW

File: internal/server/data/token.go [hunk 1]
```diff
@@ -51,6 +52,7 @@ func createJWT(db *gorm.DB, identity *models.Identity, groups []string, expires
 	custom := claims.Custom{
 		Name:   identity.Name,
 		Groups: groups,
+		Nonce:  generate.MathRandom(10),
```
Comment (BruceMacD) [inline internal/server/data/token.go:55]: This is a math random rather than a crypto random to not drain the entropy on a field that is not used.

**Review by mxyng — APPROVED** [review]
