### PR TITLE
api: consolidate DatabaseMiddleware into other middleware

### LINKED ISSUE #2697: api: failing to commit a transaction does not result in a 500 response
## Describe the bug

This bug report is based on code inspection. I haven't yet reproduced the issue with a test.

We commit a transaction from `DatabaseMiddleware`: https://github.com/infrahq/infra/blob/03cfb33c40b2f5c90e5d3486ece65fc27a76e983/internal/server/middleware.go#L41-L48

The commit error is only logged, and only at the debug level.  Simply changing this to `sendAPIError` won't work either, because it's too late in the flow of the request. Earlier in the flow we do this:
https://github.com/infrahq/infra/blob/03cfb33c40b2f5c90e5d3486ece65fc27a76e983/internal/server/routes.go#L198

`gin` does attempt to cache a status header for a bit before writing it, but it must write the headers before the body, and that call to `c.JSON` writes the response body. So by the time the `DatabaseMiddleware` calls `COMMIT`, we've already sent a success status header.

This bug would mislead users into thinking their operation was successful, when in reality the transaction commit failed, so the operation was not applied.

## Possible solution

I think we need to manage transactions differently. We should start one transaction for middlewares (`AuthenticationMiddleware` and `DestinationMiddelware`, which we can likely combine into one middleware that calls functions for the two operations , related: https://github.com/infrahq/internal/issues/19). That transaction will likely always be a write transaction (even for `GET` requests), because we must update the user `lastSeenAt`, and possibly the destination `lastSeenAt`. The middleware transaction should be committed before the handler starts.

In `wrappedHandler` we can start a transaction appropriate for the HTTP method. This gives us the opportunity to use different isolation levels based on the method or endpoint. Before writing the HTTP headers the transaction will be committed (for POST, PUT, PATCH, or DELETE), so that we can handle the error from commit before sending a successful status code. GET methods should probably always rollback.

### PR DESCRIPTION
**Pull request by dnephin**
## Summary

This PR consolidates `DatabaseMiddleware` into the existing `authenticatedMiddleware` and `unauthenticatedMiddleware`. This removes the need for these middleware to fetch the txn from `gin.Context`, they can use the txn directly.

This is the first step to fixing #2697. We'll need to do one of the following next, both of which require this change. Either we
1. use one txn for middleware, and a separate one for handlers. The txn for handlers would be managed from `wrappedHandler`.  This is my preference because it allows us to use different read modes, and isolation modes for the middleware and the handler.
2. use a single txn for both middleware and handlers, which would require moving the `(un)authenticatedMiddleware` into `wrappedHandler`. I think integrating those two is nice either way, but I like keeping separate txn.

Best viewed by individual commit.

## Related Issues

This moves us closer to being able to fix issue #2697
Related to https://github.com/infrahq/internal/issues/19

### CODE REVIEW

File: internal/server/middleware.go [hunk 1]
```diff
@@ -81,42 +67,61 @@ func handleInfraDestinationHeader(c *gin.Context) error {
...
-func authenticatedMiddleware() gin.HandlerFunc {
+func authenticatedMiddleware(db *gorm.DB) gin.HandlerFunc {
 	return func(c *gin.Context) {
-		db := getDB(c)
-		authned, err := requireAccessKey(db, c.Request)
-		if err != nil {
-			sendAPIError(c, err)
-			return
-		}
+		withDBTxn(c.Request.Context(), db, func(tx *gorm.DB) {
```
Comment (dnephin) [inline internal/server/middleware.go:75]: It's unfortunate this adds another level of indentation.

In the future, when we remove gorm, we'll have to replace this with calls to `Begin`, `Commit`, and `Rollback`. I expect that to change this code a little bit, but probably not too much.

File: internal/server/routes.go [hunk 2]
```diff
@@ -268,15 +265,14 @@ type WellKnownJWKResponse struct {
 }
 
 func (a *API) wellKnownJWKsHandler(c *gin.Context) {
-	keys, err := access.GetPublicJWK(c)
+	rCtx := getRequestContext(c)
```
Comment (dnephin) [inline internal/server/routes.go:268]: We could further integrate this `wellKnownJWKsHandler` and make it one of our `HandlerFunc`. That's going to be a prerequisite for other changes, so I might try and do that here.

I also need to check if we have test coverage for this endpoint.

Comment (dnephin) [reply internal/server/routes.go]: I did this in the latest commit.

**Review by BruceMacD — COMMENTED** [review]
The changes seem ok but I'm a bit confused about the actual scenario this is an issue. We debug log the error in the database middleware, but I am not sure what kind of errors we would get that aren't handled by the authenticated middleware `sendAPIError`

**Comment by dnephin** [comment]
> I am not sure what kind of errors we would get that aren't handled by the authenticated middleware

The transaction commit can return an error, and right now we hide it in debug logs, where as we should be returning it as an error to the user (https://github.com/infrahq/infra/issues/2697). If the transaction commit failed, then the entire operation failed because nothing was applied to the DB.

**Review by BruceMacD — APPROVED** [review]
