### PR TITLE
fix: check password policy for username/password signup

### LINKED ISSUE #4076: First sign-up does not check password against "weak passwords" file
## Describe the bug
When a user signs-up they can choose any password.

## Expected behavior
The user must pick a password that is not in the "common passwords" file.

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

Check password policy when signing up with username and password. The signup endpoint previously was not using the same password policy checker as every other similar endpoints. This means when the bad passwords checking was added in #3963, signup was missed.

Resolves #4076

### CODE REVIEW

File: internal/access/credential.go [hunk 1]
```diff
@@ -86,10 +86,16 @@ func ResetCredential(rCtx RequestContext, user *models.Identity, newPassword str
 		return "", fmt.Errorf("get credential: %w", err)
 	}
 
+	hash, err := bcrypt.GenerateFromPassword([]byte(newPassword), bcrypt.DefaultCost)
```
Comment (BruceMacD) [inline internal/access/credential.go:89]: Why doesn't this hash come from the `GenerateFromPassword` function used elsewhere?

Comment (BruceMacD) [inline internal/access/credential.go:89]: This hashing feels like it might make more sense in the `server` or `data` packages rather than the `access` check, although I see it was here previously too

Comment (mxyng) [reply internal/access/credential.go:89]: The password in this case is generated so it doesn't need to be validated against the password policy

Comment (mxyng) [reply internal/access/credential.go:89]: `access` seems to be the right place. It's where a lot of decision regarding password generation and policy are made. If this hashing is done too early (in `server),`, there's not a lot that can be done wrt password policy. If it's done too late (in `data)`, many of these decision need to be delayed or exceptions has to be made.

**Review by BruceMacD — APPROVED** [review]
