### PR TITLE
fix: hides expired keys by default

### LINKED ISSUE #2087: `infra keys list` shows expired keys
## Describe the bug

`infra keys list` still shows keys even after they have expired. This list can get really long if there are multiple login requests and so cleanup is necessary.

## Expected behavior

Either completely hiding the expired keys or only showing them with a verbose/all flag. 

## Screenshots

ple com yesterday

## Environment

```
$ infra version

Client: 0.13.0
Server: 0.13.0
```

### PR DESCRIPTION
**Pull request by j-sneh**
## Summary

Hides the listing of expired keys unless explicitly enabled.

## Checklist

- [x] Wrote appropriate unit tests 
- [x] Considered security implications of the change
- [x] Updated associated docs where necessary
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2087

### CODE REVIEW

File: api/types.go [hunk 1]
```diff
@@ -69,6 +69,10 @@ func (t Time) Equal(other Time) bool {
 	return time.Time(t).Equal(time.Time(other))
 }
 
+func (t Time) Expired(expiry Time) bool {
+	return time.Time(t).Before(time.Time(expiry))
```
Comment (BruceMacD) [inline api/types.go:73]: Does timezone have any effect on this (ie: should this be converting to UTC)?

File: api/types.go [hunk 2]
```diff
@@ -71,6 +71,10 @@ func (t Time) Equal(other Time) bool {
 	return time.Time(t).Equal(time.Time(other))
 }
 
+func (t Time) Expired(expiry Time) bool {
+	return time.Time(t).UTC().Before(time.Time(expiry).UTC())
+}
```
Comment (dnephin) [inline api/types.go:76]: This `api.Time` type could be used for all kinds of things, not necessarily only for expiry times. 

Since this method is only used in tests, I think it would be better to keep this logic in the test rather than expose it as a method.

File: internal/cmd/keys.go [hunk 3]
```diff
@@ -219,6 +221,6 @@ func newKeysListCmd(cli *CLI) *cobra.Command {
 	}
 
 	cmd.Flags().StringVar(&options.UserName, "user", "", "The name of a user to list access keys for")
-
+	cmd.Flags().BoolVar(&options.ShowExpired, "show-expired", false, "Show expired access keys")
```
[the remark this answers is not in the document]
Comment (mxyng) [reply internal/cmd/keys.go]: I would call this `--all` instead since it'll list both expired and unexpired grants

File: internal/server/data/selectors.go [hunk 4]
```diff
@@ -119,8 +121,13 @@ func ByUserID(userID uid.ID) SelectorFunc {
 	}
 }
 
-func ByPagination(pg models.Pagination) SelectorFunc {
+func ByNotExpired() SelectorFunc {
+	return func(db *gorm.DB) *gorm.DB {
+		return db.Where("expires_at is null or expires_at > ?", time.Now().UTC()).Or("expires_at is ?", time.Time{})
```
Comment (dnephin) [inline internal/server/data/selectors.go:126]: Isn't the `OR` in here twice? Once in the first statement and again because of the `.Or(...)` ?

**Review by dnephin — COMMENTED** [review]
Looks good, just a couple questions/suggestions

File: internal/cmd/keys.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (dnephin) [reply internal/cmd/keys.go]: The risk with `--all` is that in the future if we have other filters it's less obvious what `--all` should do. Should it change to show all the things hidden by default?

Something like `--show-expired` is nice because the behaviour should not need to change even when we default hide other keys.

File: internal/server/data/selectors.go (hunk 4 above)
Comment (j-sneh) [reply internal/server/data/selectors.go:126]: these are three different checks: expiration, null, and UTC 0. I can change all of them to `.Or` for consistency.

File: internal/cmd/keys.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (j-sneh) [reply internal/cmd/keys.go]: I think I'm going to go with show-expired because it's the most detailed/accurate. Although I'm also a fan of one word flags, this keeps it consistent with the API and we already have some multi-word flags.

**Review by BruceMacD — APPROVED** [review]
Looks good 👍
