### PR TITLE
fix: load google as a provider for identity

### LINKED ISSUE #3809: Social login not shown in user identity provider icons
## Describe the bug
When a user logs in via Google social login the "Users" page in the UI shows their provider as Infra only. No Google icon is shown.

## Expected behavior
The Google icon is displayed.

## Additional context
This feature is only in dev currently.

### PR DESCRIPTION
**Pull request by BruceMacD**
- pass context to list, get, and delete identities to store if google social login is enabled
- outer join provider users loading to return 0 provider ID records
- add google social provider to context

## Summary
Google social login was not being added as a name in user's identity provider name returned from the API. This was due to the `INNER JOIN` provider look-up not returning records with a 0  provider ID.

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged

## Related Issues

Resolves #3809

### CODE REVIEW

File: internal/server/data/identity.go [hunk 1]
```diff
@@ -374,7 +375,7 @@ type ListIdentityOptions struct {
 	LoadPublicKeys         bool
 }
 
-func ListIdentities(tx ReadTxn, opts ListIdentityOptions) ([]models.Identity, error) {
+func ListIdentities(c context.Context, tx ReadTxn, opts ListIdentityOptions) ([]models.Identity, error) {
```
Comment (dnephin) [inline internal/server/data/identity.go:378]: There's a `context.Context` in our transaction. We could expose that with a `Context()` method, but I think we probably don't need to be handling this in `data`. We can include the google provider in the API handler.

File: internal/server/routes.go [hunk 2]
```diff
@@ -250,6 +251,9 @@ func wrapRoute[Req, Res any](a *API, routeID routeIdentifier, route route[Req, R
 			Response:      &access.ResponseMetadata{},
 		}
 		c.Set(access.RequestContextKey, rCtx)
+		if a.server.Google != nil {
+			c.Set(data.GoogleProviderContextKey, a.server.Google)
```
Comment (dnephin) [inline internal/server/routes.go:255]: We need a way to include some `Server` data on `RequestContext`. I've been thinking a new field like `Server` would allow us to do that. That would remove the need to set anything on `gin.Context`. The API handler for `ListProviders` could read the field directly.

Here we would simply set `Server: a.server`.

**Review by dnephin — COMMENTED** [review]
Does this need to be done in the `data` package? It seems like this required a lot of changes. 

What if we use add the provider from `API.ListProviders` instead, and let the data layer return empty values for the built-in google provider?

File: internal/server/routes.go (hunk 2 above)
Comment (BruceMacD) [reply internal/server/routes.go]: Update to not use the context after our discussion

File: internal/server/data/identity.go (hunk 1 above)
Comment (BruceMacD) [reply internal/server/data/identity.go]: Updated to not use the context after our discussion

**Review by dnephin — APPROVED** [review]
Nice! I guess the name and URL could also be constants, along with the ID. 

This looks great!
