### PR TITLE
fix: rename texts and add modal

### LINKED ISSUE #3256: Inconsistent button sizes in add user modal
Screen Shot 2022-09-19 at 9 14 15 AM

### PR DESCRIPTION
**Pull request by hoyyeva**
## Related Issues
Resolves #3256

### CODE REVIEW

File: ui/pages/providers/add.js [hunk 1]
```diff
@@ -183,7 +183,7 @@ export default function ProvidersAddDetails() {
                     key={p.name}
                     onClick={() => {
                       setKind(p.kind)
-                      setName(p.kind)
+                      setName(p.kind === 'azure' ? 'active directory' : p.kind)
```
Comment (jmorganca) [inline ui/pages/providers/add.js:186]: `azure ad` might be better for the default name

**Review by jmorganca — APPROVED** [review]
Small suggestion otherwise LGTM
