### PR TITLE
Fix response body for unknown paths

### LINKED ISSUE #3161: Non-existent API routes returns an HTML response
## Describe the bug

The UI proxy acts as a catch-all route for incoming requests. This has the side effect of routing any unknown endpoints to the UI even if the route is part of the API, e.g. `/api/nonexistent`. The request, being served by the UI, returns a HTML 404 instead of a JSON 404. For an API consumer this will be confusing.

## Expected behavior

Requests to `/api/*` should return an API response, not a UI response, e.g. a JSON 404 message.
Requests not to `/api/*` can return a UI response.

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #3161

This problem is most obvious when a new client is making requests to an old server that does not yet have the new API path. Previously the response would be an HTML page from the UI. With this fix it should be a JSON API error response, which is much easier to debug.

The test for this was updated to enable the UI proxy, so that the test covers the same scenario as production. I had to also switch from `httptest.ResponseRecorder` to `httptest.Server`, because the response recorder does not work with the proxy (it would panic).

I found https://stackoverflow.com/questions/36357791/gin-router-path-segment-conflicts-with-existing-wildcard, which confirms this is a difficult problem to solve. One of the options there is to use a middleware (which is actually our problem), but it gave me the idea of just ignoring these paths in our middleware.

### CODE REVIEW

File: internal/server/server.go [hunk 1]
```diff
@@ -257,22 +257,27 @@ func runTelemetryHeartbeat(ctx context.Context, tel *Telemetry) error {
...
+		req.URL.Host = remote.Host
+	}
+	proxy.ErrorLog = log.New(logging.NewFilteredHTTPLogger(), "", 0)
+
+	router.Use(func(c *gin.Context) {
+		// Don't proxy /api/* paths
+		if strings.HasPrefix(c.Request.URL.Path, "/api/") {
+			c.Next()
+			return
+		}
```
Comment (dnephin) [inline internal/server/server.go:277]: Maybe not the most elegant solution, but this is the only one I could find. See the stackoverflow I linked in the description for a very long answer about possible workarounds to this problem.

File: internal/server/server.go [hunk 2]
```diff
@@ -257,22 +257,27 @@ func runTelemetryHeartbeat(ctx context.Context, tel *Telemetry) error {
...
-			req.URL.Scheme = remote.Scheme
-			req.URL.Host = remote.Host
-		}
-		proxy.ErrorLog = log.New(logging.NewFilteredHTTPLogger(), "", 0)
-
-		router.Use(func(c *gin.Context) {
-			proxy.ServeHTTP(c.Writer, c.Request)
-			c.Abort()
-		})
+	if opts.ProxyURL.Host == "" {
```
Comment (dnephin) [inline internal/server/server.go:260]: I swapped this condition to a guard so that we can return early. Best viewed with [Hide Whitespace](https://github.com/infrahq/infra/pull/3567/files?diff=split&w=1)

File: internal/server/server.go (hunk 1 above)
Comment (BruceMacD) [reply internal/server/server.go:277]: This seems like a fine solution to me

**Review by BruceMacD — COMMENTED** [review]
What's the actual error returned now?

**Comment by dnephin** [comment]
>What's the actual error returned now?

It's a 404 response code, but with a full page of HTML in the response body. I guess it's whatever the UI sends for its 404 page.

**Review by BruceMacD — APPROVED** [review]

**Review by mxyng — APPROVED** [review]
