### PR TITLE
fix: remove non-secure cookies on logout

### LINKED ISSUE #4003: Logging out from social login may not clear the session cookie
## Describe the bug
When a user signs in via social login (ie: Google) the cookie they get for their session may not be cleared from the browser on logout.

## Expected behavior
The cookie is cleared.

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
When logging out on an `http` connection the cookie is not cleared, check if the incoming request is secure to clear this cookie.

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged

## Related Issues

Resolves #4003

### CODE REVIEW

File: internal/server/cookie.go [hunk 1]
```diff
@@ -47,13 +47,19 @@ func setCookie(req *http.Request, resp http.ResponseWriter, config cookieConfig)
 	})
 }
 
-func deleteCookie(resp http.ResponseWriter, name, domain string) {
+func deleteCookie(req *http.Request, resp http.ResponseWriter, name, domain string) {
+	secure := true
+	if req.TLS == nil {
```
Comment (jmorganca) [inline internal/server/cookie.go:52]: Is this for testing? Or another reason?

Comment (BruceMacD) [reply internal/server/cookie.go:52]: Assuming that the cookies the client has are `secure` if the request is over `https`, and not otherwise because we need to set the cookie to clear it, and secure cookies cannot be set over http channels. 

`http` is only used during testing locally. Hosted Infra should always be over HTTPs.

Comment (jmorganca) [reply internal/server/cookie.go:52]: Ah I see this is simply making this functionality the same as elsewhere, and that makes sense for consistency. LGTM

**Review by jmorganca — APPROVED** [review]
