### PR TITLE
fix: deleting provider doesn't update the table until refresh

### LINKED ISSUE #2771: ui: deleting provider doesn't update provider table

### PR DESCRIPTION
**Pull request by hoyyeva**
## Related Issues
Resolves #2771

### CODE REVIEW

File: ui/pages/providers/index.js [hunk 1]
```diff
@@ -72,19 +70,8 @@ function SidebarContent({ provider, admin, setSelectedProvider }) {
...
-                  await fetch(`/api/providers/${provider.id}`, {
-                    method: 'DELETE',
-                  })
-
-                  return { items: providers.filter(p => p?.id !== provider.id) }
-                }
-              )
-
-              setSelectedProvider(null)
+            onRemove={async () => {
```
Comment (jmorganca) [inline ui/pages/providers/index.js:73]: No need for `async` anymore

**Review by jmorganca — APPROVED** [review]
