### PR TITLE
fix: remove provider users for deleted identities

### LINKED ISSUE #3397: When an identity is soft-deleted provider user records should be removed
## Describe the bug
When an identity is deleted we don't clean up the "provider_user" records that correspond with this identity. These records are used to track where an identity exists, but do not provide an access.

## Expected behavior
When the identity record that corresponds to a "provider_user" record is deleted we should also remove the "provider_user" tracking.

## Environment

```
$ infra version
Client: 0.15.2
```

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
This should be merged after #3398
When an identity was deleted through the CLI the associated provider user was not deleted. This migration cleans up provider_user records that reference a deleted identity.

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #3397

### CODE REVIEW

File: internal/server/data/migrations_test.go [hunk 1]
```diff
@@ -728,6 +728,29 @@ DELETE FROM settings WHERE id=24567;
...
+				_, err := db.Exec("DELETE FROM identities")
+				assert.NilError(t, err)
+				_, err = db.Exec("DELETE FROM provider_users")
+				assert.NilError(t, err)
+			},
+			expected: func(t *testing.T, db WriteTxn) {
+				var remainingProviderUser uid.ID
+				err := db.QueryRow(`SELECT identity_id FROM provider_users`).Scan(&remainingProviderUser)
+				assert.NilError(t, err)
+				assert.Equal(t, remainingProviderUser, uid.ID(2222))
```
Comment (dnephin) [inline internal/server/data/migrations_test.go:751]: minor: I think this test could pass even when the first record is not deleted, if the DB decided to return the records in a different order than we expect. I'm not sure if that's possible. 
Another option might be to `SELECT count(*) from provider_users where identity_id = 1111` which should give us a count of 0.

**Review by dnephin — APPROVED** [review]
LGTM
