### PR TITLE
Fix request scoped transactions

### LINKED ISSUE #2697: api: failing to commit a transaction does not result in a 500 response
## Describe the bug

This bug report is based on code inspection. I haven't yet reproduced the issue with a test.

We commit a transaction from `DatabaseMiddleware`: https://github.com/infrahq/infra/blob/03cfb33c40b2f5c90e5d3486ece65fc27a76e983/internal/server/middleware.go#L41-L48

The commit error is only logged, and only at the debug level.  Simply changing this to `sendAPIError` won't work either, because it's too late in the flow of the request. Earlier in the flow we do this:
https://github.com/infrahq/infra/blob/03cfb33c40b2f5c90e5d3486ece65fc27a76e983/internal/server/routes.go#L198

`gin` does attempt to cache a status header for a bit before writing it, but it must write the headers before the body, and that call to `c.JSON` writes the response body. So by the time the `DatabaseMiddleware` calls `COMMIT`, we've already sent a success status header.

This bug would mislead users into thinking their operation was successful, when in reality the transaction commit failed, so the operation was not applied.

## Possible solution

I think we need to manage transactions differently. We should start one transaction for middlewares (`AuthenticationMiddleware` and `DestinationMiddelware`, which we can likely combine into one middleware that calls functions for the two operations , related: https://github.com/infrahq/internal/issues/19). That transaction will likely always be a write transaction (even for `GET` requests), because we must update the user `lastSeenAt`, and possibly the destination `lastSeenAt`. The middleware transaction should be committed before the handler starts.

In `wrappedHandler` we can start a transaction appropriate for the HTTP method. This gives us the opportunity to use different isolation levels based on the method or endpoint. Before writing the HTTP headers the transaction will be committed (for POST, PUT, PATCH, or DELETE), so that we can handle the error from commit before sending a successful status code. GET methods should probably always rollback.

### LINKED ISSUE #3076: Rollback transactions in middleware does not have an effect
## Describe the bug
The way we currently handle runtime errors means that errors are never fully bubbled up to our middleware database transaction, so errors would not cause a database transaction rollback.

## Expected behavior
Database transactions are handled in a way that can receive the error and rollback appropriately. 

## Environment
- Infra version <=0.14.5

## Additional context
```
// middleware.go
func withDBTxn(ctx context.Context, db *gorm.DB, fn func(tx *gorm.DB)) {
	err := db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		fn(tx)
                // need to return an error here if the function fails
		return nil
	})
	// TODO: https://github.com/infrahq/infra/issues/2697
	if err != nil {
		logging.L.Error().Err(err).Msg("failed to commit database transaction")
	}
}
```

### PR DESCRIPTION
**Pull request by dnephin**
## Summary

Branched from #3028 this PR cleans up the commits from #3032 to fix both #2697 and #3076  

We had two problems with our request scoped transactions:
1. the transaction was never rolled back on error, it was always comitted
2. we never reported a failure to commit a transaction to the user

This PR addresses the problems by:
* moving the transaction to `wrapRoute`, which has access to the error from both the middleware and the handlers
* in `wrapRoute` add a defer which will rollback if commit has not happened
* and respond with a 500 response code if the transaction fails to commit

## Related Issues

Resolves #2697
Resolves #3076

### CODE REVIEW

File: internal/server/debug.go [hunk 1]
```diff
@@ -6,14 +6,14 @@ import (
 
 	"github.com/gin-gonic/gin"
 
+	"github.com/infrahq/infra/api"
 	"github.com/infrahq/infra/internal/access"
 	"github.com/infrahq/infra/internal/server/models"
 )
 
-func pprofHandler(c *gin.Context) {
+func pprofHandler(c *gin.Context, _ *api.EmptyRequest) (*api.EmptyResponse, error) {
```
Comment (dnephin) [inline internal/server/debug.go:14]: Now that the database transaction comes from `wrapRoute` this handler had to be updated to fit the interface required by `wrapRoute`.

File: internal/server/routes_test.go [hunk 2]
```diff
@@ -108,30 +108,6 @@ func TestBindsEmptyRequest(t *testing.T) {
 	assert.NilError(t, err)
 }
 
-func TestGetRoute(t *testing.T) {
```
Comment (dnephin) [inline internal/server/routes_test.go:111]: I think this test was probably useful before, but now it does not really do much. We have good test coverage for all of our real production routes, so we don't need to test an artificial route.

File: internal/server/middleware.go [hunk 3]
```diff
@@ -70,40 +70,31 @@ func handleInfraDestinationHeader(c *gin.Context) error {
 // authenticatedMiddleware is applied to all routes that require authentication.
 // It validates the access key, and updates the lastSeenAt of the user, and
 // possibly also of the destination.
-func authenticatedMiddleware(srv *Server) gin.HandlerFunc {
```
Comment (BruceMacD) [inline internal/server/middleware.go:73]: I think the name "authenticatedMiddleware" is confusing here where this is just an auth check and scope now, it doesnt actually pass the request through any middleware

File: internal/server/routes.go [hunk 4]
```diff
@@ -140,43 +147,97 @@ func (s *Server) GenerateRoutes() Routes {
...
+
+	handler := func(c *gin.Context) {
+		if err := wrapRoute(a, route)(c); err != nil {
+			sendAPIError(c, err)
+		}
+	}
+	bindRoute(a, group.RouterGroup, route.method, route.path, handler)
+}
+
+func wrapRoute[Req, Res any](a *API, route route[Req, Res]) func(*gin.Context) error {
```
Comment (BruceMacD) [inline internal/server/routes.go:186]: I would like to see a comment explaining that `wrapRoute` effectively functions as a middleware for requests, there is a lot going on in here

**Review by BruceMacD — APPROVED** [review]

File: internal/server/middleware.go (hunk 3 above)
Comment (dnephin) [reply internal/server/middleware.go:73]: Very true, I'll rename this to remove "middlware", and I should also update the godoc at the same time.

File: internal/server/routes.go (hunk 4 above)
Comment (dnephin) [reply internal/server/routes.go:186]: Good call, there is a lot going on here. #3104 is a follow up PR that reduces it a bit.

More godoc here would be better. I'll add that now.

File: internal/server/middleware.go (hunk 3 above)
Comment (dnephin) [reply internal/server/middleware.go:73]: I pushed a commit that renames these to `authenticateRequest`, and `validateRequestOrganization`. What do you think of those names?
