### PR TITLE
fix: create one kubeconfig context per destination

### LINKED ISSUE #3611: Only create one kubeconfig context per cluster
We can continue to set the namespace in the context if they only have access to one namespace, otherwise we can leave it blank and they'll have to specify the namespace to kubectl.

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

create only one kubeconfig context per destination regardless if there may be multiple namespaces granted to the user.

update `use` to set the `Namespace` field of the target context.

Resolves #3611

### CODE REVIEW

File: internal/cmd/kubernetes.go [hunk 1]
```diff
@@ -85,80 +85,78 @@ func writeKubeconfig(user *api.User, destinations []api.Destination, grants []ap
...
 		}
 
-		if !exists {
+		if infraContext.URL == "" {
 			continue
 		}
 
-		u, err := urlx.Parse(url)
+		contextName := "infra:" + cluster
+		if _, ok := infraContexts[contextName]; ok && namespace != "" {
```
Comment (mxyng) [inline internal/cmd/kubernetes.go:125]: If there's a non-namespace grant, set that as the default context. Otherwise, pick a namespace

**Review by BruceMacD — COMMENTED** [review]
Looks good once checks pass

**Review by dnephin — COMMENTED** [review]
I have a hard time following `writeKubeconfig`.

Do we have a test case for each of these cases that you could point me at?
1. a user with access to multiple namespaces gets a single context with no namespace set
2. a user with access to a single namespace gets a single context with the namespace set
3. a user with access to the full cluster (not a single namespace) gets a single context with no namespace set

**Comment by mxyng** [comment]
Good call out on the tests. It was definitely missing some cases. I've refactored the test so it should be easier to follow and added the missing cases

File: internal/cmd/kubernetes_test.go [hunk 2]
```diff
@@ -48,123 +43,123 @@ func TestWriteKubeconfig(t *testing.T) {
...
-func TestWriteKubeconfig_UserNamespaceOverride(t *testing.T) {
-	home := t.TempDir()
-	t.Setenv("HOME", home)
-	t.Setenv("USERPROFILE", home)
+	t.Run("MultipleNamespaces", func(t *testing.T) {
+		expectedContexts := map[string]*clientcmdapi.Context{
+			"infra:connected": {
+				AuthInfo:  "user",
+				Cluster:   "infra:connected",
+				Namespace: "namespace",
```
Comment (dnephin) [inline internal/cmd/kubernetes_test.go:107]: I thought the expectation would be for `Namespace: ""`, since this user has access to multiple namespaces. Is this test expecting the right thing?

**Review by dnephin — COMMENTED** [review]
Nice! The tests look great now! I'll try and give `writeKubeconfig` a more detailed read tomorrow. One question about the tests

File: internal/cmd/kubernetes_test.go (hunk 2 above)
Comment (mxyng) [reply internal/cmd/kubernetes_test.go:107]: `Namespace: ""` is equivalent to `Namespace: "default"` which the user may not have access to. It makes sense to set `Namespace` to something as long as the user doesn't have some form of global access. We can probably introduce heuristics to make the selection smarter but for now, it'll pick the first namespace user has access to.

Comment (dnephin) [reply internal/cmd/kubernetes_test.go:107]: I guess if one of the namespaces they have access to is default, then it would make sense for that to be the namespace. If they don't have access to default then any arbitrary one seems reasonable.

File: internal/cmd/kubernetes.go [hunk 3]
```diff
@@ -85,80 +85,82 @@ func writeKubeconfig(user *api.User, destinations []api.Destination, grants []ap
...
 				break
 			}
 		}
 
-		if !exists {
+		if infraContext.URL == "" {
+			continue
+		}
+
+		contextName := "infra:" + cluster
```
Comment (jmorganca) [inline internal/cmd/kubernetes.go:128]: nit: could check this and `continue` earlier in the function

File: internal/cmd/kubernetes.go [hunk 4]
```diff
@@ -85,80 +85,82 @@ func writeKubeconfig(user *api.User, destinations []api.Destination, grants []ap
 		return err
 	}
 
-	keep := make(map[string]bool)
+	type clusterContext struct {
```
Comment (jmorganca) [inline internal/cmd/kubernetes.go:88]:
```suggestion
	type context struct {
```

File: internal/cmd/kubernetes.go [hunk 5]
```diff
@@ -85,80 +85,82 @@ func writeKubeconfig(user *api.User, destinations []api.Destination, grants []ap
...
+		Namespace string
+		URL       string
+		CA        []byte
+	}
+
+	infraContexts := make(map[string]clusterContext)
```
Comment (jmorganca) [inline internal/cmd/kubernetes.go:94]:
```suggestion
	contexts := make(map[string]context)
```

File: internal/cmd/kubernetes.go [hunk 6]
```diff
@@ -85,80 +85,82 @@ func writeKubeconfig(user *api.User, destinations []api.Destination, grants []ap
...
+		if _, ok := infraContexts[contextName]; ok && namespace != "" {
 			continue
 		}
 
-		u, err := urlx.Parse(url)
+		infraContext.Namespace = namespace
+		infraContexts[contextName] = infraContext
+	}
+
+	for contextName, infraContext := range infraContexts {
```
Comment (jmorganca) [inline internal/cmd/kubernetes.go:137]:
```suggestion
	for name, context := range contexts {
```

**Review by jmorganca — COMMENTED** [review]
Nit: some of the naming could be simplified/tightened

**Comment by jmorganca** [comment]
Looks good! Some super minor comments

File: internal/cmd/kubernetes.go (hunk 4 above)
Comment (mxyng) [reply internal/cmd/kubernetes.go:88]: I wanted to avoid clobbering the `context` package

Comment (jmorganca) [reply internal/cmd/kubernetes.go:88]: Good call!
