### PR TITLE
fix: do not set a otp on machine identities

### LINKED ISSUE #1622: Do not create OTP for machine identity
## Describe the bug
When a machine identity is created in the CLI it should not get a one time password.

## Expected behavior
When a machine identity is created no authentication mechanism is set by default

## Environment

```
$ infra version
```

```
$ kubectl version
```

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
There was a bug in identity creation through the CLI that would set a one time password on machine identities by default. Fixing this behavior to not set a one time password on machine identity creation.

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged

## Related Issues

Resolves #1622

### CODE REVIEW

File: internal/cmd/identities.go [hunk 1]
```diff
@@ -247,6 +247,10 @@ func CreateIdentity(req *api.CreateIdentityRequest) (*api.CreateIdentityResponse
 
 	req.Kind = kind.String()
 
+	if kind == "machine" {
+		req.SetOneTimePassword = false
+	}
```
Comment (mxyng) [inline internal/cmd/identities.go:252]: This does not prevent the user from send a request for a machine user with `SetOneTimePassword=true`. Would it be better to have this check/mutation server-side?

Comment (BruceMacD) [reply internal/cmd/identities.go]: Made this change

**Review by dnephin — APPROVED** [review]
LGTM!

**Review by jmorganca — APPROVED** [review]
