### PR TITLE
fix: rollback postgres db transaction on fail

### LINKED ISSUE #2652: Server does not properly propogate duplicate grant error on postgres
## Describe the bug

<!-- A clear and concise description of what the bug is. -->

When a duplicate grant is added, the server responds with 500 Internal Server Error.

```
$ infra grants add admin@email.com docker-desktop --role exec                                                                                                                                                                                                                                                                                                                                                                                                                                                
Created grant to "docker-desktop" for "admin@email.com"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
$ infra grants add admin@email.com docker-desktop --role exec                                                                                                                                                                                                                                                                                                                                                                                                                                                
Error: internal server error
```

Infra Server logs:
```
{"rows":0,"level":"error","caller":"data/data.go:162","elapsed":8.766984,"error":"ERROR: duplicate key value violates unique constraint \"idx_grant_srp\" (SQLSTATE 23505)","time":1658266217630,"query":"INSERT INTO \"grants\" (\"created_at\",\"updated_at\",\"deleted_at\",\"subject\",\"privilege\",\"resource\",\"created_by\",\"id\") VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING \"id\""}
{"rows":0,"level":"error","caller":"data/data.go:131","elapsed":1.063427,"error":"ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","time":1658266217632,"query":"SELECT count(*) FROM \"grants\" WHERE subject = $1 AND privilege = $2 AND resource = $3 AND \"grants\".\"deleted_at\" IS NULL"}
{"error": "has grants: ERROR: current transaction is aborted, commands ignored until end of transaction block (SQLSTATE 25P02)","level": "error","caller": "server/routes.go:158","remoteAddr": "192.168.9.49:56490","time": 1658266217632,"path": "/api/grants","method": "POST","statusCode": 500}
```

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

Same result as SQLite

### PR DESCRIPTION
**Pull request by BruceMacD**
- postgres db transaction needs to be rolled back on failure or it can't be re-used to make other database requests

## Summary
Postgres was failing with an internal server error on duplicate grant creation. The reason for this is that Postgres closes the DB transaction on error, but we would then attempt to read the existing grant on the same transaction.

Fix (as suggested by Steven) is to rollback the failed query in the case of a postgres database. 

This replaces the previous PR for the same issue: #2658 

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated docs where necessary
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2652

### CODE REVIEW

File: internal/server/data/data.go [hunk 1]
```diff
@@ -155,7 +155,18 @@ func save[T models.Modelable](db *gorm.DB, model *T) error {
 }
 
 func add[T models.Modelable](db *gorm.DB, model *T) error {
-	err := db.Create(model).Error
+	var err error
```
Comment (BruceMacD) [inline internal/server/data/data.go:158]: I didn't add this rollback logic to `save` because I couldn't think of a scenario we would expect an error when calling that function. If you can think of something let me know and I'll add it to `save` to.

**Review by dnephin — APPROVED** [review]
LGTM
