### PR TITLE
fix: password reset sending multiple requests

### LINKED ISSUE #3114: Password reset button can be clicked multiple times producing multiple emails
## Describe the bug

The password reset button takes a non-zero amount of time to disappear which gives the user ample opportunity to click it more. This results in multiple emails being sent to the recipient. 

image

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

Set `submitted` state as soon as the submit button is pressed rather than after the request returns.

Also some minor UI issues like
* punctuation
* divider on password reset
* margin between forgot password and login button

Resolves #3114

### CODE REVIEW

File: ui/pages/password-reset/index.js [hunk 1]
```diff
@@ -99,7 +91,10 @@ export default function PasswordReset() {
                   />
                 </div>
                 <button
-                  disabled={!email}
+                  disabled={submitted}
+                  onClick={() => {
+                    setSubmitted(true)
```
Comment (jmorganca) [inline ui/pages/password-reset/index.js:96]: Thanks for fixing!

This should be set `onSubmit` handler above (vs writing this new handler)

File: ui/pages/password-reset/index.js [hunk 2]
```diff
@@ -13,6 +13,7 @@ export default function PasswordReset() {
   const [submitted, setSubmitted] = useState(false)
 
   async function onSubmit(e) {
+    setSubmitted(true)
```
Comment (BruceMacD) [inline ui/pages/password-reset/index.js:16]: You may want to set this back to false on error so the user can try again.

Comment (mxyng) [reply ui/pages/password-reset/index.js:15]: Good call out though but the UI doesn't currently branch on errors. The error state is never set to a non-empty value so I've removed it

**Review by BruceMacD — APPROVED** [review]
