### PR TITLE
fix: sidebar and setting page flashes bug

### LINKED ISSUE #2596: ui: sidebar flashes when adding a user to a group
Sidebar flashes when adding a user to a group

Screen Shot 2022-07-14 at 8 49 19 PM

### PR DESCRIPTION
**Pull request by hoyyeva**
## Related Issues
Resolves #2596

### CODE REVIEW

File: ui/pages/groups/index.js [hunk 1]
```diff
@@ -115,111 +115,117 @@ function Details({ group, admin, onDelete }) {
...
                   await fetch(`/api/groups/${id}/users`, {
                     method: 'PATCH',
-                    body: JSON.stringify({ usersToRemove }),
-                  })
-                  mutateUsers({
-                    items: users.filter(i => i.id !== userId),
+                    body: JSON.stringify({ usersToAdd }),
                   })
+
+                  mutateUsers({ items: [...users, ...emails] })
```
Comment (hoyyeva) [inline ui/pages/groups/index.js:176]: instead of calling the endpoint like this `mutateUsers(`/api/users?group=${group.id}`)`, we can just do `items: [...users, ...emails]` to update the  dom

**Review by BruceMacD — APPROVED** [review]
