### PR TITLE
fix: allow infra prefix for `infra use`

### LINKED ISSUE #2095: `infra use infra:<cluster name>` fails
Since we name the Kubernetes context `infra:<cluster name>`, we should support users who run `infra use infra:<cluster name>` vs just `infra use <cluster name>`

Today, Infra converts the `:` to a `.` and it fails:

```
$ infra use infra:digitalocean
ERROR  context not found: infra.digitalocean
```

### PR DESCRIPTION
**Pull request by j-sneh**
## Summary

Since a cluster is "officially" named infra:<cluster-name> in Kubernetes, this change allows a user to both write `infra use infra:name` and `infra use name`
## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated docs where necessary
~~Updated associated configuration where necessary~~
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
~~Considered data migrations for smooth upgrades~~

## Related Issues

Resolves #2095

### CODE REVIEW

File: internal/cmd/cmd.go [hunk 1]
```diff
@@ -119,7 +119,9 @@ func newUseCmd(_ *CLI) *cobra.Command {
 $ infra use development
 
 # Use a Kubernetes namespace context
-$ infra use development.kube-system`,
+$ infra use development.kube-system
+
+# Note: infra:<cluster-name> is equivalent to <cluster-name>`,
```
Comment (jmorganca) [inline internal/cmd/cmd.go:124]: We can remove this help text, since handling `infra:` is more of an exception / user error we're catching here

File: internal/cmd/cmd_test.go [hunk 2]
```diff
@@ -196,6 +196,24 @@ func TestUse(t *testing.T) {
 		assert.Assert(t, is.Contains(kubeconfig.AuthInfos, "testuser@example.com"))
 	})
 
+	t.Run("InfraUse", func(t *testing.T) {
```
Comment (jmorganca) [inline internal/cmd/cmd_test.go:199]: Nice work with this test!

File: internal/cmd/kubernetes.go [hunk 3]
```diff
@@ -33,10 +33,11 @@ func kubernetesSetContext(cluster, namespace string) error {
 		return err
 	}
 
-	name := cluster
+	name := strings.TrimPrefix(cluster, "infra:")
+	fmt.Println(cluster, name)
```
Comment (jmorganca) [inline internal/cmd/kubernetes.go:37]: Remove me

**Review by jmorganca — CHANGES_REQUESTED** [review]
Nice work! A few comments

File: internal/cmd/kubernetes.go (hunk 3 above)
Comment (j-sneh) [reply internal/cmd/kubernetes.go:37]: haha oops

**Review by jmorganca — APPROVED** [review]
