### PR TITLE
fix: user list is sorted on create and update

### LINKED ISSUE #1711: ui: changing cluster role causes row ordering to change
Screen Shot 2022-04-25 at 9 40 51 PM

### PR DESCRIPTION
**Pull request by hoyyeva**
## Summary
- the cluster share user list is sorted by user id, so the list will not reorder when update the role
- change text grant to share

## Related Issues
Resolves #1711

### CODE REVIEW

File: ui/components/grant.js [hunk 1]
```diff
@@ -8,11 +8,14 @@ import ErrorMessage from '../components/error-message'
 import InfoModal from './modals/info'
 
 function Grant ({ id }) {
-  const { data: user } = useSWR(`/v1/identities/${id.replace('i:', '')}`, { fallbackData: { name: '' } })
-
-  return (
-    <p>{user.name}</p>
-  )
+  if (id) {
```
Comment (jmorganca) [inline ui/components/grant.js:11]: Would fast-return here:

```
if (!id) {
  return null
}
```

**Review by jmorganca — APPROVED** [review]

**Review by jmorganca — APPROVED** [review]
