### PR TITLE
fix: cluster-specific ca for generating connector certificates

### LINKED ISSUE #1637: Avoid use of SNI
Many Kubernetes clients don't have great SNI support (e.g. javascript-based ones)

We should generate a CA with the connectors and generate self-signed certs from that CA with the proper SAN fields instead of relying on SNI since many clients don't have this.

Potentially helpful: https://helm.sh/docs/chart_template_guide/function_list/#genca

### PR DESCRIPTION
**Pull request by jmorganca**
Fixes #1637

### CODE REVIEW

File: internal/connector/connector.go [hunk 1]
```diff
@@ -320,37 +318,47 @@ func Run(ctx context.Context, options Options) error {
...
+	validServernames.Store("127.0.0.1", true)
+	validServernames.Store("infra-connector", true)
 
-		if err := manager.Cache.Put(context.TODO(), serverName, certBytes); err != nil {
-			return err
+	// Generate TLS certificates on the fly for clients
+	// GenerateCertificate caches certificates
+	tlsConfig := &tls.Config{MinVersion: tls.VersionTLS12}
+	tlsConfig.GetCertificate = func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
+		servername := hello.ServerName
```
Comment (ssoroka) [inline internal/connector/connector.go:355]: servername might be missing if client doesn't support it

**Review by ssoroka — APPROVED** [review]

File: internal/connector/connector.go (hunk 1 above)
Comment (jmorganca) [reply internal/connector/connector.go]: Great catch! Updated since the prior approach wouldn't work for IP addresses

**Review by mxyng — APPROVED** [review]

**Comment by jmorganca** [comment]
@mxyng @ssoroka  thanks for the review!
