### PR TITLE
fix: allow direct access key for idp user

### LINKED ISSUE #2895: api fails to update identity information from provider when using an access key directly
Create an access key for a user provided by Okta (or Google/Azure AD) and use it imperatively:

```
export INFRA_SERVER=infra.acme.com
export INFRA_ACCESS_KEY=x.y
infra login
infra use cluster
kubectl get pods
```

This will sometimes fail with 401 since when trying to sync with the identity provider

```
{"level":"info","error":"unauthorized: failed to update identity info from provider: record not found","method":"POST","path":"/api/tokens","statusCode":401,"remoteAddr":"192.168.205.197:33360","time":1660086393611,"caller":"server/routes.go:170","message":"api request error"}
```

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
Moving this check for the provider sync fixes a bug where issuing an access key directly to a user from an identity provider did not work. Also added test coverage to the `/tokens` endpoint. 

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated docs where necessary
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2895

### CODE REVIEW

File: internal/server/tokens_test.go [hunk 1]
```diff
@@ -0,0 +1,202 @@
...
+	"github.com/infrahq/infra/internal/server/data"
+	"github.com/infrahq/infra/internal/server/models"
+	"github.com/infrahq/infra/internal/server/providers"
+)
+
+func TestAPI_CreateToken(t *testing.T) {
+	srv := setupServer(t, withAdminUser)
+	routes := srv.GenerateRoutes(prometheus.NewRegistry())
+
+	_, err := data.InitializeSettings(srv.db)
```
Comment (dnephin) [inline internal/server/tokens_test.go:23]: This is unexported in `main`, and is done automatically as part of `setupServer`. Should hopefully be fine to just remove this line.

File: internal/server/tokens_test.go [hunk 2]
```diff
@@ -0,0 +1,202 @@
...
+					ProviderID: data.InfraProvider(srv.db).ID,
+					ExpiresAt:  time.Now().Add(10 * time.Second),
+				}
+				accessKey, err := data.CreateAccessKey(srv.db, key)
+				assert.NilError(t, err)
+
+				req.Header.Set("Authorization", "Bearer "+accessKey)
+			},
+			expected: func(t *testing.T, resp *httptest.ResponseRecorder) {
+				assert.NilError(t, err)
```
Comment (dnephin) [inline internal/server/tokens_test.go:73]: I think this is checking an error from outside the test case

```suggestion
```

File: internal/server/tokens_test.go [hunk 3]
```diff
@@ -0,0 +1,202 @@
...
+				assert.Equal(t, resp.Code, http.StatusCreated)
```
Comment (dnephin) [inline internal/server/tokens_test.go:74]: A check for the contents of `resp.Body` would be great too in one of these cases. Not blocking though, this is great additional test coverage.

**Review by dnephin — APPROVED** [review]
Looks great! There's a build failure, but should be an easy fix
