### PR TITLE
fix(ui): minor display issues in UI

### LINKED ISSUE #2235: ui: long emails truncated in bottom left
## Describe the bug

Long emails truncated in bottom left menu

## Screenshots

Screen Shot 2022-06-13 at 9 58 38 AM

### PR DESCRIPTION
**Pull request by jmorganca**
Fixes #2235, #2407 

Also fixes an issue where the user & group dropdown wouldn't update options after re-focusing

### CODE REVIEW

File: ui/pages/providers/add/details.js [hunk 1]
```diff
@@ -99,8 +99,6 @@ export default function ProvidersAddDetails() {
           </label>
           <input
             required
```
Comment (hoyyeva) [inline ui/pages/providers/add/details.js:101]: this doesn't show the 1Password in the input container?

Comment (jmorganca) [reply ui/pages/providers/add/details.js:101]: Great catch!! Will revert this

**Review by hoyyeva — APPROVED** [review]
