### PR TITLE
fix: remove deleted identities from identities_groups

### LINKED ISSUE #2766: users aren't removed from `identities_groups` table when removed from infra
## Describe the bug

Users aren't removed from identities_groups when running `infra users rm user@example.com`, they're only removed if removed from the group itself. This causes `group.UserCount` to be off.

## Expected behavior

Users should be removed from identities_groups when removed from infra, probably through a call to `data.RemoveUsersFromGroup`

## Environment

```
$ infra version
0.14.3+dev
```

```
$ kubectl version
```

### PR DESCRIPTION
**Pull request by j-sneh**
## Summary

Deleted users were still showing up in the `identities_groups` table, as though they still had group membership. This caused `group.UserCount` to be off.

This change removes users from all groups on user deletion and adds a migration to remove previously deleted users from groups.

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [ ] Updated associated docs where necessary
- [ ] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2766

### CODE REVIEW

File: internal/access/identity.go [hunk 1]
```diff
@@ -80,6 +80,16 @@ func DeleteIdentity(c *gin.Context, id uid.ID) error {
 		return fmt.Errorf("delete identity access keys: %w", err)
 	}
 
+	groups, err := data.ListGroups(db, nil, data.ByGroupMember(id))
+	if err != nil {
+		return fmt.Errorf("delete identity from groups: %w", err)
```
Comment (BruceMacD) [inline internal/access/identity.go:85]:
```suggestion
		return fmt.Errorf("deleted identity group membership: %w", err)
```

I'd like to have a different message here from the actual error removing the user, so we can differentiate them.

**Review by BruceMacD — COMMENTED** [review]
Thanks for fixing this, I think adding a check for the group removal to the identity_test would be good too

File: internal/access/identity_test.go [hunk 2]
```diff
@@ -81,6 +82,13 @@ func TestDeleteIdentityCleansUpResources(t *testing.T) {
 	err = data.CreateGrant(db, grantDestination)
 	assert.NilError(t, err)
 
+	err = data.CreateGroup(db, &models.Group{Name: "Group"})
+	assert.NilError(t, err)
+	groups, err := data.ListGroups(db, nil)
+	assert.NilError(t, err)
+	err = data.AddUsersToGroup(db, groups[0].ID, []uid.ID{identity.ID})
```
Comment (dnephin) [inline internal/access/identity_test.go:89]: I think you can get the `group.ID` this way without needing to list:

```suggestion
	group := &models.Group{Name: "Group"}
	err = data.CreateGroup(db, group)
	assert.NilError(t, err)
	err = data.AddUsersToGroup(db, group.ID, []uid.ID{identity.ID})
```

This works because `CreateGroup` sets the ID on the passed in pointer, so we can access it after the call to `CreateGroup`.

File: internal/server/data/identity.go [hunk 3]
```diff
@@ -124,6 +124,18 @@ func DeleteIdentities(db *gorm.DB, selectors ...SelectorFunc) error {
 		if err != nil {
 			return err
 		}
+
+		groups, err := ListGroups(db, nil, ByGroupMember(i.ID))
```
Comment (dnephin) [inline internal/server/data/identity.go:128]: We should add a test for this change as well

**Review by dnephin — COMMENTED** [review]
Looks great! I think this is just missing test coverage for `access.DeleteIdentities`.

I opened #2838 to resolve the fact that we have two flows that handle this logic in different places. This PR doesn't introduce the problem, so I think we should merge this fix and address it later.

**Review by dnephin — APPROVED** [review]
