### PR TITLE
fix: sort custom role

### LINKED ISSUE #2772: ui: place custom roles at the bottom of the role list
When showing custom roles without descriptions, we should put them at the bottom of the role dropdown list. They currently show up in another order and this may be off-putting to newer users:

Screen Shot 2022-07-28 at 8 27 31 PM

### PR DESCRIPTION
**Pull request by hoyyeva**
## Related Issues
Resolves #2772

### CODE REVIEW

File: ui/components/role-select.js [hunk 1]
```diff
@@ -33,9 +27,11 @@ export default function RoleSelect({
     () =>
       resource && `/api/destinations?name=${hasParent ? parts[0] : resource}`
   )
+
   roles = roles || items?.[0]?.roles || []
   roles = roles
     ?.sort(sortByPrivilege)
+    ?.sort(sortByHasDescriptions)
```
Comment (jmorganca) [inline ui/components/role-select.js:34]: nit: `sortByHasDescription` since there's only one description per role?

File: ui/lib/grants.js [hunk 2]
```diff
@@ -10,6 +20,20 @@ export function sortByPrivilege(a, b) {
   return a?.privilege?.localeCompare(b?.privilege)
 }
 
+export function sortByHasDescriptions(a, b) {
+  const descriptionsList = Object.keys(descriptions)
+
+  if (descriptionsList.includes(a)) {
```
Comment (jmorganca) [inline ui/lib/grants.js:26]: Can just do `if (descriptions[a]) {...`

**Comment by jmorganca** [comment]
Nice work - a few small comments

**Review by jmorganca — APPROVED** [review]
🚀
