### PR TITLE
fix: ui bugs

### LINKED ISSUE #2103: ui: a non admin user should not be able to see remove button on infrastructure page

### LINKED ISSUE #2114: ui: the name icon is not centered
Image

### PR DESCRIPTION
**Pull request by hoyyeva**
## Related Issues
Resolves #2114 
Resolves #2103

### CODE REVIEW

File: ui/pages/users/index.js [hunk 1]
```diff
@@ -20,7 +20,7 @@ const columns = [{
   accessor: u => u,
   Cell: ({ value: user }) => (
     <div className='flex items-center py-1.5'>
-      <ProfileIcon name={user.name[0]} />
+      <ProfileIcon name={user.name[0]} size='28px' />
```
Comment (jmorganca) [inline ui/pages/users/index.js:23]: Elegant. Nice work with the `size` prop!

**Review by jmorganca — APPROVED** [review]
