### PR TITLE
fix: password confirmation field and minor improvements

### LINKED ISSUE #2108: ui: change password dialog improvement
change password dialog doesn't have a password confirmation field

### LINKED ISSUE #2373: ui lets you create unusable and invalid password
## Describe the bug

When logging in on account creation using the temporary password, users are able to create a password of less than 8, which isn't rejected. However, when logging in again later the password is invalid and requires a reset.

## Expected behavior

The UI should prevent you from creating an invalid password.

## Environment

```
$ infra version
```

```
$ kubectl version
```

### PR DESCRIPTION
**Pull request by hoyyeva**
## Summary
- added password confirmation field on signup and initial password reset (#2108)
Screen Shot 2022-07-04 at 12 01 51 PM
Screen Shot 2022-07-04 at 11 53 06 AM

- prevent user to reset password that is invalid (#2373)
Screen Shot 2022-07-04 at 11 37 28 AM

- improve confirmation password field error handling
Screen Shot 2022-07-04 at 12 22 34 PM

## Related Issues
Resolves #2108 
Resolves #2373

### CODE REVIEW

File: ui/pages/settings/password-reset.js [hunk 1]
```diff
@@ -41,9 +42,18 @@ export default function PasswordReset() {
         throw data
       }
 
-      router.replace('/settings?resetPassword=success')
+      await router.replace('/settings?resetPassword=success')
```
Comment (jmorganca) [inline ui/pages/settings/password-reset.js:45]: Don't need `await` here

File: ui/pages/signup/index.js [hunk 2]
```diff
@@ -52,7 +57,7 @@ export default function Signup() {
       await mutate('/api/signup')
       await mutate('/api/users/self')
 
-      router.replace('/')
+      await router.replace('/')
```
Comment (jmorganca) [inline ui/pages/signup/index.js:60]: No need for `await`

File: ui/pages/settings/password-reset.js [hunk 3]
```diff
@@ -15,17 +15,18 @@ export default function PasswordReset() {
...
   const [error, setError] = useState('')
+  const [errors, setErrors] = useState({})
 
   async function onSubmit(e) {
     e.preventDefault()
 
     if (password !== confirmPassword) {
-      setError('password does not match')
+      setErrors({
+        confirmPassword: 'the confirm password confirmation does not match.',
```
Comment (jmorganca) [inline ui/pages/settings/password-reset.js:25]: `passwords do not match` is a more concise error message for this

**Review by jmorganca — APPROVED** [review]
