### PR TITLE
fix: do not make external API calls in tests

### LINKED ISSUE #2949: IDP test should not require external call to get OIDC info
## Describe the bug
Tests loading config are calling out to a demo okta endpoint and attempting to load info. 

## Expected behavior
It should mock the response from this endpoint.

See `internal/server/config_test.go`

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
- Remove domains that may be called externally in the case of a bad test configuration
- Remove migration test that makes external call

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2949

### CODE REVIEW

File: internal/server/config_test.go [hunk 1]
```diff
@@ -691,9 +699,11 @@ func TestLoadConfigPruneConfig(t *testing.T) {
 		Providers: []Provider{
 			{
 				Name:         "okta",
-				URL:          "new-demo.okta.com",
+				URL:          "new.example.com",
 				ClientID:     "new-client-id",
 				ClientSecret: "new-client-secret",
+				AuthURL:      "new.example.com/auth",
```
Comment (BruceMacD) [inline internal/server/config_test.go:705]: These missing from this test were causing a failure due to an external call

File: internal/server/data/migrations_test.go [hunk 2]
```diff
@@ -166,31 +163,28 @@ INSERT INTO providers (id, created_at, updated_at, deleted_at, name, url, client
...
+					actual = append(actual, p)
 				}
 
-				assert.Equal(t, len(providers), 2)
-				authUrls := make(map[string]string)
-				scopes := make(map[string][]string)
-				for _, p := range providers {
-					authUrls[p.Name] = p.AuthURL
-					scopes[p.Name] = p.Scopes
+				// updated := parseTime(t, "2022-07-05 17:13:14.172568+00")
```
Comment (dnephin) [inline internal/server/data/migrations_test.go:179]: left over debugging ?
```suggestion
```

File: internal/server/data/migrations_test.go [hunk 3]
```diff
@@ -151,12 +150,10 @@ func TestMigrations(t *testing.T) {
 			},
 		},
 		{
-			// this test does an external call to example.okta.com, if it fails check your network connection
 			label: testCaseLine("202206281027"),
 			setup: func(t *testing.T, db *gorm.DB) {
 				stmt := `
 INSERT INTO providers (id, created_at, updated_at, deleted_at, name, url, client_id, client_secret, kind, created_by) VALUES (67301777540980736, '2022-07-05 17:13:14.172568+00', '2022-07-05 17:13:14.172568+00', NULL, 'infra', '', '', 'AAAAEIRG2/PYF2erJG6cYHTybucGYWVzZ2NtBDjJTEEbL3Jvb3QvLmluZnJhL3NxbGl0ZTMuZGIua2V5DGt4MdtlZuxOUhZQTw', 'infra', 1);
-INSERT INTO providers (id, created_at, updated_at, deleted_at, name, url, client_id, client_secret, kind, created_by) VALUES (67301777540980737, '2022-07-05 17:13:14.172568+00', '2022-07-05 17:13:14.172568+00', NULL, 'okta', 'example.okta.com', 'client-id', 'AAAAEIRG2/PYF2erJG6cYHTybucGYWVzZ2NtBDjJTEEbL3Jvb3QvLmluZnJhL3NxbGl0ZTMuZGIua2V5DGt4MdtlZuxOUhZQTw', 'okta', 1);
```
Comment (dnephin) [inline internal/server/data/migrations_test.go:159]: If we remove this, we are no longer testing the migration. We can't show that a non-infra provider has a kind set.  Can we keep it?

Comment (BruceMacD) [reply internal/server/data/migrations_test.go:159]: Kind being set is tested separately in `202206151027`. I'll add this back for now though, this migration will probably be removed soon anyway 👍

File: internal/server/data/migrations_test.go (hunk 2 above)
Comment (BruceMacD) [reply internal/server/data/migrations_test.go]: it was, thanks

File: internal/server/data/migrations_test.go (hunk 3 above)
Comment (BruceMacD) [reply internal/server/data/migrations_test.go]: Brought it back

**Review by dnephin — APPROVED** [review]
Looks good!
