### PR TITLE
fix: only template out kubeconfig for k8s destinations

### LINKED ISSUE #3920: SSH destinations are added to the generated Kubeconfig
When running `infra login`, `infra list` or `infra use`, SSH destinations are added to the kubeconfig:

```
...
- cluster:
    certificate-authority-data: <redacted>
    server: https://<redacted>
  name: infra:amazon-linux
...
```

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

Only K8s destinations should get entries in kubeconfig.

Resolves #3920

### CODE REVIEW

**Review by jmorganca — COMMENTED** [review]
Looks like a good cleanup so far!

File: internal/cmd/kubernetes_test.go [hunk 1]
```diff
@@ -14,8 +15,112 @@ import (
...
+	serverOpts.Config.Grants = []server.Grant{
+		{
+			User:     "admin@local",
+			Resource: "infra",
+			Role:     "admin",
+		},
+		{
+			User:     "admin@local",
+			Resource: "my-first-kubernetes-cluster",
+			// Role: "admin",
```
Comment (jmorganca) [inline internal/cmd/kubernetes_test.go:42]:
```suggestion
```

File: internal/cmd/kubernetes_test.go [hunk 2]
```diff
@@ -14,8 +15,112 @@ import (
...
+		},
+		{
+			User:     "admin@local",
+			Resource: "my-first-ssh-server",
+			// Role: "admin",
```
Comment (jmorganca) [inline internal/cmd/kubernetes_test.go:47]:
```suggestion
```

**Review by jmorganca — APPROVED** [review]
