### PR TITLE
fix: improve grants list performance

### LINKED ISSUE #2231: CLI: infra grants list is too slow
with ~300 grants infra grants list command can take > 30s to respond.

Sounds like the client is doing too many requests. From the code it looks like it's doing O(2n) queries, which is way too many.

### PR DESCRIPTION
**Pull request by mxyng**
## Summary

Grants list queries the server for each user or group which is exceedingly slow when more than a few users/groups exist. It's also unnecessary in a lot of use cases because users and groups will be duplicated for multiple grants. Instead, retrieve a list of users and groups once and lookup the user when necessary

Old code:

```
$ /usr/bin/time -h infra grants list | grep USER
  USER (7702)        ACCESS         DESTINATION
        20.20s real             1.21s user              0.82s sys
```

New code:

```
$ /usr/bin/time -h infra grants list | grep USER
  USER (7702)        ACCESS         DESTINATION
        0.28s real              0.14s user              0.05s sys
```

Tested against local Infra server with a permutation of ~100 users, 7 roles, and 10 destinations

## Checklist

- [ ] Wrote appropriate unit tests
- [ ] Considered security implications of the change
- [ ] Updated associated docs where necessary
- [ ] Updated associated configuration where necessary
- [ ] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [ ] Nothing sensitive logged
- [ ] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2231

### CODE REVIEW

File: internal/cmd/grants.go [hunk 1]
```diff
@@ -132,6 +83,86 @@ func newGrantsListCmd(cli *CLI) *cobra.Command {
 	return cmd
 }
 
+func userGrants(cli *CLI, client *api.Client, grants *api.ListResponse[api.Grant]) (int, error) {
```
Comment (mxyng) [inline internal/cmd/grants.go:86]: would be nice to use generics here since the code is _very_ similar between this and `groupGrants` but the table headers are different so not sure how to genericize it

**Review by BruceMacD — APPROVED** [review]
I'm ok with the repetition between functions here, my solution would be to make the rows named types with a shared "append"-like function, but I am not sure if that's really any cleaner.
