### PR TITLE
fix: get refresh token on google login

### LINKED ISSUE #3917: UI Login Flow does not get refresh token from Google
## Describe the bug
No refresh token is retrieved from Google on OIDC login through the UI.

## Expected behavior
The consent prompt and access_type parameters are set in redirect for Google login in the UI. 
```
if provider.Kind == "google" {
    params.Add("prompt", "consent")      // google only sends a refresh token when a user consents, always prompt so we always get the ref token
    params.Add("access_type", "offline") // specifies that we want a refresh token
}
```

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
In order to extend get a refresh token from Google additional parameters must be specified on OIDC login. This was done in the CLI but the UI was out of sync here.

Add the required parameters for Google sign-up and login to get a refresh token from Google.

This change is made in 2 places. #3909 removes the duplicate code.

## Checklist

- [x] Considered security implications of the change
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged

## Related Issues

Resolves #3917

### CODE REVIEW

**Review by ssoroka — APPROVED** [review]

File: ui/components/providers.js [hunk 1]
```diff
@@ -48,9 +48,22 @@ function oidc(id, clientID, authURL, scopes, redirectURL, next) {
...
-  )}&state=${state}`
+  const sendTo = new URL(authURL)
+  // URL searchParams add query parameters to a URL
+  sendTo.searchParams.append('redirect_uri', redirectURL)
+  sendTo.searchParams.append('client_id', clientID)
+  sendTo.searchParams.append('response_type', 'code')
+  sendTo.searchParams.append('scope', scopes.join(' '))
+  sendTo.searchParams.append('state', state)
+
+  if (kind === 'google') {
```
Comment (jmorganca) [inline ui/components/providers.js:59]: Is there any harm in _always_ adding these params?

Comment (BruceMacD) [reply ui/components/providers.js:59]: In the case of Azure it means an extra step approving permissions every time you login, so I'd like to keep it specific for now.

File: ui/pages/login/index.js [hunk 2]
```diff
@@ -49,9 +49,22 @@ function oidcLogin(
...
+  sendTo.searchParams.append('client_id', clientID)
+  sendTo.searchParams.append('response_type', 'code')
+  sendTo.searchParams.append('scope', scopes.join(' '))
+  sendTo.searchParams.append('state', state)
+
+  if (kind === 'google') {
+    // google only sends a refresh token when a user consents, always prompt so we always get the ref token
+    sendTo.searchParams.append('prompt', 'consent')
+    // also need to specify offline access in the case of Google to get a refresh token
+    sendTo.searchParams.append('access_type', 'offline')
```
Comment (jmorganca) [inline ui/pages/login/index.js:64]: Shouldn't we always include this (for Okta, others too)?

File: ui/components/providers.js (hunk 1 above)
Comment (jmorganca) [reply ui/components/providers.js:59]: Thanks!

**Review by jmorganca — APPROVED** [review]
