### PR TITLE
fix: a few bugs on grants and deletion

### LINKED ISSUE #2027: ui: group grants don't render in grant list
Screen Shot 2022-05-24 at 10 14 20 AM

### LINKED ISSUE #2039: ui: deletion modal
the new design for the deletion modal - https://www.figma.com/file/RD3lsWESwo1QykjaT4IB7y/UI-Milestone-1?node-id=895%3A4833

### PR DESCRIPTION
**Pull request by hoyyeva**
## Summary
- new deletion modal
Screen Shot 2022-05-25 at 3 04 39 PM

- api migration
- filter groups on destination access
- filter `connector` on user management 

## Related Issues
Resolves #2039
Resolves #2027

### CODE REVIEW

File: ui/components/grant.js [hunk 1]
```diff
@@ -21,8 +21,9 @@ function User ({ id }) {
 
 export default function ({ id }) {
   const { data: destination } = useSWR(`/api/destinations/${id}`)
-  const { data: { items: list } = {} } = useSWR(() => `/api/grants?resource=${destination.name}`)
+  const { data: { items } = {} } = useSWR(() => `/api/grants?resource=${destination.name}`)
   const { mutate } = useSWRConfig()
+  const list = items?.filter(item => item.user !== undefined)
```
Comment (jmorganca) [inline ui/components/grant.js:26]: Taking away the check against `undefined`, while seeming ambiguous, will catch other potential cases like `null`:

Checking `!!item.user` works too

```suggestion
  const list = items?.filter(item => item.user)
```

**Review by jmorganca — APPROVED** [review]
Small suggestion otherwise LGTM!
