### PR TITLE
fix: kube config permissions user read/write

### LINKED ISSUE #2699: Set `.kube/config` file permissions to not be world/group readable
## Describe the bug
When running helm I see an output error:
```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /Users/bruce/.kube/config
```

## Expected behavior
The kube config is created with the right read/write permissions to not output this warning.

## Environment

```
$ infra version        

 Client: 0.14.0
 Server: 0.14.0
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/arm64"}
```

## Additional context
I believe this is from #2610 
```
	if err := clientcmd.WriteToFile(kubeconfig, config.ConfigAccess().GetDefaultFilename()); err != nil {
		return err
	}
```

### PR DESCRIPTION
**Pull request by BruceMacD**
## Summary
You may have noticed warnings about kube config file permissions. This fixes the permissions to be only user read/write.

os.Create sets the file to world and group readable, this causes kubectl to warn the user, revert to ioutil.TempFile which sets the kube config to 0o600. This is still Windows compatible because it explicitly closes the file, so it won't cause a regression of #2586.

## Checklist

- [x] Wrote appropriate unit tests
- [x] Considered security implications of the change
- [x] Updated associated docs where necessary
- [x] Updated associated configuration where necessary
- [x] Change is backwards compatible if it needs to be (user can upgrade without manual steps?)
- [x] Nothing sensitive logged
- [x] Considered data migrations for smooth upgrades

## Related Issues

Resolves #2699

### CODE REVIEW

File: internal/cmd/kubernetes_test.go [hunk 1]
```diff
@@ -57,6 +59,12 @@ func TestWriteKubeconfig(t *testing.T) {
 		},
 	}
 
+	configFileStats, err := os.Stat(kubeConfigPath)
+	assert.NilError(t, err)
+
+	permissions := configFileStats.Mode().Perm()
+	assert.Assert(t, permissions == 0o600) // kube config should not be world or group readable, only user read/write
```
Comment (BruceMacD) [inline internal/cmd/kubernetes_test.go:66]: I have to check that his permissions test work on Windows also, its using Unix file permissions.

Comment (dnephin) [reply internal/cmd/kubernetes_test.go:66]: `assert.Equal` would give better failure messages here

**Review by dnephin — APPROVED** [review]
LGTM
